package contracts.tag

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    description "idempotent set of an article's tags; ids are generated by the monolith and reused by name when the tag exists"
    request {
        method PUT()
        url "/internal/articles/a1000000-0000-0000-0000-000000000001/tags"
        headers {
            contentType applicationJson()
            header "Authorization": $(consumer(regex("Token .+")), producer("Token valid-jwt-for-u1"))
        }
        body(
                tags: [
                        [id: "t1000000-0000-0000-0000-000000000001", name: "java"],
                        [id: "t2000000-0000-0000-0000-000000000002", name: "spring"]
                ]
        )
    }
    response {
        status NO_CONTENT()
    }
}
