package io.spring.application.tag.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A {@code tags} row; {@code id} is generated by the monolith ({@code io.spring.core.article.Tag}).
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TagDto {
  private String id;
  private String name;
}
