package io.spring.application.comment.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request body of {@code POST /internal/articles/{articleId}/comments}. {@code id} and {@code
 * createdAt} (ISO-8601) are generated by the monolith so a dual-written row is identical.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class NewCommentRequest {
  private String id;
  private String body;
  private String userId;
  private String createdAt;
}
