package io.spring.application.article.dto;

import io.spring.application.tag.dto.TagDto;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request body of {@code POST /internal/articles}. {@code id}, {@code slug}, {@code createdAt}
 * (ISO-8601) and the tag ids are generated by the monolith so a dual-written row is identical.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class NewArticleRequest {
  private String id;
  private String slug;
  private String title;
  private String description;
  private String body;
  private String userId;
  private String createdAt;
  private List<TagDto> tags;
}
